language: php

php:
  - 5.6

env:
  - DEPENDENCIES=""
  - DEPENDENCIES="--prefer-lowest"

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --no-interaction $DEPENDENCIES

script:
  - composer analyze
  - vendor/bin/phpunit --coverage-clover coverage-clover.xml
